"""Generate validation records by MEASUREMENT. Never by hand.

    python -m research.validate            # compute, print, write nothing
    python -m research.validate --write    # persist to data/validation.json

This closes the last structural hole in the bot. `bot/validation.py` checks
records; until now nothing produced them, so the only way to get a passing
record was to type one -- which would have made the gate a formality dressed
as a control.

This module runs the full battery and writes whatever it finds, PASSING OR
FAILING. Writing the failures matters as much as writing the passes: a stored
failing record tells the gate exactly why a strategy is refused, and it stops
anyone from later "just adding" a record because none existed.

**It cannot be argued with.** The thresholds live in `bot/validation.py` and
this module never sets `survives_concentration` or a t-statistic by hand -- it
computes them and hands over the result.

The honesty caveat that applies to today's candidate, recorded in the record's
own `notes` field: 12-2 was selected AFTER seeing full-sample results for all
three formations. So the holdout below is contaminated by that selection and
is weaker evidence than a true out-of-sample window. The fix is not a better
statistic, it is data we have not looked at yet -- CRSP, when it arrives.
"""

from __future__ import annotations

import argparse
import math
import statistics
import sys
from collections import defaultdict
from datetime import date

from bot.validation import Registry, ValidationRecord
from research.cross_momentum import (DECILE, FORMATIONS, NULL_SEEDS, ann,
                                     load_prices, month_ends, run, sharpe)

REGISTRY_PATH = "data/validation.json"


def paired_t(diffs: list[float]) -> float:
    if len(diffs) < 2:
        return math.nan
    se = statistics.stdev(diffs) / math.sqrt(len(diffs))
    return statistics.mean(diffs) / se if se else math.nan


def measure_momentum(form: int, skip: int, cost_bp: float = 5.0):
    """The full battery for one formation. Returns everything the record needs."""
    dates, px, _ = load_prices()
    mes = month_ends(dates)

    strat, months = run(mes, px, form, skip, cost_bp, None)
    by_month = defaultdict(list)
    for s in range(NULL_SEEDS):
        nr, nm = run(mes, px, form, skip, cost_bp, seed=1000 + s)
        for m, v in zip(nm, nr):
            by_month[m].append(v)
    null = [statistics.mean(by_month[m]) for m in months]
    diffs = [a - b for a, b in zip(strat, null)]

    # Concentration: does the edge survive losing its best 1% of periods?
    k = max(1, int(round(0.01 * len(diffs))))
    cut = sorted(diffs)[:-k]

    # Holdout: last 30%. Contaminated by formation selection -- see the module
    # docstring. Recorded honestly rather than dressed up.
    h = int(0.7 * len(diffs))

    return dict(
        n=len(strat), months=months, strat=strat, null=null, diffs=diffs,
        mean_excess=statistics.mean(diffs) if diffs else math.nan,
        t_vs_null=paired_t(diffs),
        t_concentrated=paired_t(cut),
        survives_concentration=(paired_t(cut) > 0 and paired_t(diffs) > 0),
        holdout_t=paired_t(diffs[h:]),
        first_half_t=paired_t(diffs[: len(diffs) // 2]),
        second_half_t=paired_t(diffs[len(diffs) // 2:]),
        ann_strat=ann(strat), ann_null=ann(null), sharpe=sharpe(strat),
        span=f"{months[0][:7]}..{months[-1][:7]}" if months else "?",
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="persist records to data/validation.json")
    ap.add_argument("--cost-bp", type=float, default=5.0)
    args = ap.parse_args()

    print("=" * 78)
    print("VALIDATION -- records generated by measurement")
    print("=" * 78)

    reg = Registry.load(REGISTRY_PATH)
    today = date.today().isoformat()
    made = []

    for form, skip in FORMATIONS:
        name = f"cross_momentum_{form}_{skip}"
        m = measure_momentum(form, skip, args.cost_bp)
        rec = ValidationRecord(
            signal=name,
            n_trades=m["n"],
            mean_r=m["mean_excess"],
            t_vs_null=m["t_vs_null"],
            holdout_t=m["holdout_t"],
            survives_concentration=m["survives_concentration"],
            tested_on=m["span"],
            tested_at=today,
            kind="portfolio",
            window=f"monthly/{DECILE}",
            stop_atr=float(form),
            target_atr=float(skip),
            notes=("Formation selected AFTER seeing full-sample results for all "
                   "three, so the holdout is contaminated by that choice. "
                   "Universe is 100 end-2018 large caps, ALL of which still "
                   "trade: ~100% survivorship, levels overstated. Needs CRSP."),
        )
        reg.add(rec)
        made.append((name, rec, m))

    print(f"\n  {'record':<24}{'n':>5}{'excess/mo':>11}{'t vs null':>11}"
          f"{'conc':>8}{'hold':>8}  verdict")
    print("  " + "-" * 74)
    for name, rec, m in made:
        fails = rec.failures()
        verdict = "PASS" if not fails else f"{len(fails)} failure(s)"
        print(f"  {name:<24}{rec.n_trades:>5}{1e4*rec.mean_r:>10.1f}bp"
              f"{rec.t_vs_null:>+11.2f}{m['t_concentrated']:>+8.2f}"
              f"{rec.holdout_t:>+8.2f}  {verdict}")

    print("\n  why each is refused:")
    for name, rec, _ in made:
        for f in rec.failures():
            print(f"    {name:<24} {f}")
        if not rec.failures():
            print(f"    {name:<24} -- nothing; it passes")

    best = max(made, key=lambda x: x[1].t_vs_null)
    name, rec, m = best
    print(f"\n  strongest: {name}")
    print(f"    strategy {m['ann_strat']:+.2f}%/yr vs null {m['ann_null']:+.2f}%/yr"
          f"   SR {m['sharpe']:+.2f}")
    print(f"    split-half  first {m['first_half_t']:+.2f}  "
          f"second {m['second_half_t']:+.2f}")
    print(f"    concentration {rec.t_vs_null:+.2f} -> {m['t_concentrated']:+.2f}")

    if args.write:
        reg.save(REGISTRY_PATH)
        print(f"\n  wrote {len(reg.records)} records -> {REGISTRY_PATH}")
        print("  Failing records are stored deliberately: the gate can then name")
        print("  the reason, and nobody can add a record later because none existed.")
    else:
        print(f"\n  nothing written. Re-run with --write to persist.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
